# RECUERDEN NO IGNORAR ESTE ARCHIVO, O NO LES PODREMOS CORREGIR.
DIAS_COMPETENCIA = 6
POPULARIDAD_MINIMA_DELEGACION = 0
PROBABILIDAD_ACCIDENTARSE_GIMNASIA = 0.3
NIVEL_IMPLEMENTOS = 0.1
PUNTAJE_MINIMO = 0
PATH_DEPORTISTAS = 'deportistas.csv'
PATH_DELEGACIONES = 'delegaciones.csv'
PUNTOS_ENTRENAMIENTO = 10
PATH_RESULTADOSTXT = 'resultados.txt'
# COMPLETAR...